#!/bin/bash

# Do not change order of tool
# 1. pint
# 2. rector
# 3. tests

# --------------------------------------------------------------------------
# Pint
# --------------------------------------------------------------------------
echo "[ pre-push ] 🔄 Running Pint - $(date '+%H:%M:%S')"
./vendor/bin/pint --parallel
echo "[ pre-push ] ✅ Pint finished - $(date '+%H:%M:%S')"

# --------------------------------------------------------------------------
# Rector
# --------------------------------------------------------------------------
echo "[ pre-push ] 🔄 Running Rector - $(date '+%H:%M:%S')"
./vendor/bin/rector
echo "[ pre-push ] ✅ Rector finished - $(date '+%H:%M:%S')"

# --------------------------------------------------------------------------
# Tests
# --------------------------------------------------------------------------
echo "[ pre-push ] 🔄 Running Tests - $(date '+%H:%M:%S')"
php artisan test --parallel
echo "[ pre-push ] ✅ Tests finished - $(date '+%H:%M:%S')"

# Get the branch being pushed
current_branch=$(git symbolic-ref --short HEAD)

# Define allowed branch patterns
allowed_patterns=("^feature/" "^bugfix/" "^hotfix/" "^improve/" "^staging/" "^master$")

# Check if the branch name matches any of the allowed patterns
for pattern in "${allowed_patterns[@]}"; do
  if [[ "$current_branch" =~ $pattern ]]; then
    exit 0
  fi
done

# If no match, block the push
echo "Error: Branch '$current_branch' is not allowed to push. Allowed patterns are: ${allowed_patterns[*]}"
exit 1
