<?php

return [
    'front-root' => [
        'title' => 'Mainweb',
        'url' => 'http://localhost:3000',
        'heroicon' => 'heroicon-o-presentation-chart-line',
        'icon' => null,
        'group' => 'Links',
        'sort' => 1,
    ],
    'backend-root' => [
        'title' => 'Backend Root',
        'url' => '/',
        'heroicon' => 'heroicon-o-presentation-chart-line',
        'icon' => null,
        'group' => 'Links',
        'sort' => 1,
    ],
    'chatify' => [
        'title' => 'Chatify',
        'url' => '/chatify',
        'heroicon' => 'heroicon-o-presentation-chart-line',
        'icon' => null,
        'group' => 'Tools',
        'sort' => 1,
    ],
    'backend-admin' => [
        'title' => 'Super Admin Panel',
        'url' => '/super-admin',
        'heroicon' => 'heroicon-o-presentation-chart-line',
        'icon' => null,
        'group' => 'Links',
        'sort' => 1,
    ],
    'api-doc' => [
        'title' => 'Api Docs',
        'url' => '/docs/api',
        'heroicon' => 'heroicon-o-presentation-chart-line',
        'icon' => null,
        'group' => 'Tools',
        'sort' => 2,
    ],
    'health' => [
        'title' => 'Monitoring',
        'url' => '/health?fresh',
        'heroicon' => 'heroicon-o-presentation-chart-line',
        'icon' => null,
        'group' => 'Tools',
        'sort' => 3,
    ],
    'log-viewer' => [
        'title' => 'Logging',
        'url' => '/log-viewer',
        'heroicon' => 'heroicon-o-presentation-chart-line',
        'icon' => null,
        'group' => 'Tools',
        'sort' => 4,
    ],
    'telescope' => [
        'title' => 'Telescope',
        'url' => '/telescope',
        'heroicon' => 'heroicon-o-presentation-chart-line',
        'icon' => null,
        'group' => 'Tools',
        'sort' => 5,
    ],
    'horizon' => [
        'title' => 'Horizon',
        'url' => '/horizon',
        'heroicon' => 'heroicon-o-presentation-chart-line',
        'icon' => null,
        'group' => 'Tools',
        'sort' => 6,
    ],
    'pulse' => [
        'title' => 'Pulse',
        'url' => '/pulse',
        'heroicon' => 'heroicon-o-presentation-chart-line',
        'icon' => null,
        'group' => 'Tools',
        'sort' => 7,
    ],
    'prometheus' => [
        'title' => 'Metrics',
        'url' => '/metrics',
        'heroicon' => 'heroicon-o-presentation-chart-line',
        'icon' => null,
        'group' => 'Tools',
        'sort' => 8,
    ],
];
