<?php

declare(strict_types=1);

return [
    'wakatime' => [
        'title'    => 'Wakatime',
        'url'      => 'https://wakatime.com/dashboard',
        'heroicon' => 'heroicon-s-rocket-launch',
        'icon'     => null,
        'group'    => null,
        'sort'     => 1,
    ],
    'nightwatch' => [
        'title'    => 'Nightwatch',
        'url'      => 'https://nightwatch.laravel.com/us/environments/9f2c96aa-8c28-4e01-9385-a907a4853111/dashboard',
        'heroicon' => 'heroicon-s-bug-ant',
        'icon'     => null,
        'group'    => null,
        'sort'     => 1,
    ],
    'github' => [
        'title'    => 'Github',
        'url'      => 'https://github.com/moham7dreza',
        'heroicon' => 'heroicon-o-code-bracket',
        'icon'     => null,
        'group'    => null,
        'sort'     => 1,
    ],
    'tools' => [
        'title'    => 'Tools',
        'url'      => '/tool',
        'heroicon' => 'heroicon-o-cube',
        'icon'     => null,
        'group'    => null,
        'sort'     => 1,
    ],
    'front-root' => [
        'title'    => 'Mainweb',
        'url'      => 'http://localhost:3000',
        'heroicon' => 'heroicon-o-building-storefront',
        'icon'     => null,
        'group'    => 'Links',
        'sort'     => 1,
    ],
    'backend-root' => [
        'title'    => 'Backend Root',
        'url'      => '/',
        'heroicon' => 'heroicon-o-building-office',
        'icon'     => null,
        'group'    => 'Links',
        'sort'     => 1,
    ],
    'chatify' => [
        'title'    => 'Chatify',
        'url'      => '/chatify',
        'heroicon' => 'heroicon-o-chat-bubble-left-right',
        'icon'     => null,
        'group'    => 'Tools',
        'sort'     => 1,
    ],
    'backend-admin' => [
        'title'    => 'Super Admin Panel',
        'url'      => '/super-admin',
        'heroicon' => 'heroicon-o-academic-cap',
        'icon'     => null,
        'group'    => 'Links',
        'sort'     => 1,
    ],
    'user-panel' => [
        'title'    => 'User Panel',
        'url'      => config('app.frontend_url') . '/admin',
        'heroicon' => 'heroicon-o-home-modern',
        'icon'     => null,
        'group'    => 'Links',
        'sort'     => 1,
    ],
    'api-doc' => [
        'title'    => 'Api Docs',
        'url'      => '/docs/api',
        'heroicon' => 'heroicon-o-command-line',
        'icon'     => null,
        'group'    => 'Tools',
        'sort'     => 2,
    ],
    'health' => [
        'title'    => 'Monitoring',
        'url'      => '/health?fresh',
        'heroicon' => 'heroicon-o-beaker',
        'icon'     => null,
        'group'    => 'Tools',
        'sort'     => 3,
    ],
    'log-viewer' => [
        'title'    => 'Logging',
        'url'      => '/log-viewer',
        'heroicon' => 'heroicon-o-exclamation-triangle',
        'icon'     => null,
        'group'    => 'Tools',
        'sort'     => 4,
    ],
    'telescope' => [
        'title'    => 'Telescope',
        'url'      => '/telescope',
        'heroicon' => 'heroicon-o-magnifying-glass-circle',
        'icon'     => null,
        'group'    => 'Tools',
        'sort'     => 5,
    ],
    'horizon' => [
        'title'    => 'Horizon',
        'url'      => '/horizon',
        'heroicon' => 'heroicon-o-queue-list',
        'icon'     => null,
        'group'    => 'Tools',
        'sort'     => 6,
    ],
    'pulse' => [
        'title'    => 'Pulse',
        'url'      => '/pulse',
        'heroicon' => 'heroicon-o-arrow-trending-up',
        'icon'     => null,
        'group'    => 'Tools',
        'sort'     => 7,
    ],
    'prometheus' => [
        'title'    => 'Metrics',
        'url'      => '/metrics',
        'heroicon' => 'heroicon-o-rss',
        'icon'     => null,
        'group'    => 'Tools',
        'sort'     => 8,
    ],
    'tinker' => [
        'title'    => 'Tinker',
        'url'      => '/tinker',
        'heroicon' => 'heroicon-o-command-line',
        'icon'     => null,
        'group'    => 'Tools',
        'sort'     => 9,
    ],
];
