name: Build & Test & Deployment

on:
  push:
    branches:
      - master


jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install Composer Dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Copy .env
        run: cp .env.example .env

      - name: Set Application Key
        run: php artisan key:generate

      - name: Install Front Dependencies
        run: npm ci

      - name: Build Front Dependencies
        run: npm run build

      - name: Init Sqlite
        run: touch database/database.sqlite

      - name: Migrate Database
        run: php artisan migrate --force

      - name: Run Laravel Tests
        run: php artisan test
  CD:
    needs: CI
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Production Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            (php artisan down) || true
            git pull origin master
            composer install --no-dev --optimize-autoloader
            export PATH=$PATH:/usr/local/bin:/home/$USERNAME/.nvm/versions/node/v22.14.0/bin
            npm ci
            npm run build
            php artisan optimize:clear
            php artisan migrate --force
            php artisan queue:restart
            php artisan up
